# Data persistence
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Listen interfaces
listener 1883 0.0.0.0

# Use file to store secrets
allow_anonymous true
#password_file /mosquitto/config/passwd
