services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    env_file:
      - .env

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    user: "0:0"
    restart: always
    network_mode: host
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: always
    network_mode: host
    depends_on:
      - mqtt
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - ${ZIGBEE_DONGLE}
    environment:
      - TZ=Europe/Paris

# --- To be implemented ---
# Moonraker
# Windy
# Spotify
# Telegram
# Thread
# Toyota EU
#Tuya
