services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - ./homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mqtt
    environment:
      - TZ=Europe/Paris

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./zigbee2mqtt/data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mqtt
    environment:
      - TZ=Europe/Paris

# --- To be implemented ---
# Moonraker
# Windy
# Spotify
# Telegram
# Thread
# Toyota EU
#Tuya
